In [1]:
import sympy as sym
import numpy as np

import testzd as zd

This notebook verifies the various algebraic steps required to prove the general form of an extortionate strategy $p\in\mathbb{R}^{4\times 1}$:

In [2]:
tilde_p = sym.symbols("tilde_p1:5")
R, S, T, P = sym.symbols("R, S, T, P")
alpha, beta = sym.symbols("alpha, beta")
tilde_p

(tilde_p1, tilde_p2, tilde_p3, tilde_p4)

In [3]:
eqn_1 = sym.Eq(tilde_p[0], alpha * (R - P) + beta * (R - P))
eqn_2 = sym.Eq(tilde_p[1], alpha * (S - P) + beta * (T - P))
eqn_3 = sym.Eq(tilde_p[2], alpha * (T - P) + beta * (S - P))
eqn_4 = sym.Eq(tilde_p[3], 0)

In [4]:
solved_alpha = sym.solveset(eqn_2, alpha).args[0]
solved_alpha

(-beta*(P - T) - tilde_p2)/(P - S)

Formula for $\beta$:

In [5]:
solved_beta = sym.solveset(eqn_3.subs({alpha: solved_alpha}), beta).args[0]
sym.simplify(solved_beta)

(P*tilde_p2 - P*tilde_p3 + S*tilde_p3 - T*tilde_p2)/((S - T)*(-2*P + S + T))

Formula for $\alpha$:

In [6]:
solved_alpha = solved_alpha.subs({beta: solved_beta})
sym.simplify(solved_alpha)

(P*tilde_p2 - P*tilde_p3 - S*tilde_p2 + T*tilde_p3)/(2*P*S - 2*P*T - S**2 + T**2)

Formula for $p_1$:

In [7]:
sym.simplify(eqn_1.subs({alpha: solved_alpha, beta: solved_beta}))

Eq(tilde_p1, (P*tilde_p2 + P*tilde_p3 - R*tilde_p2 - R*tilde_p3)/(2*P - S - T))

Formula for $\chi$:

In [8]:
sym.simplify(- solved_beta / solved_alpha)

(P*tilde_p2 - P*tilde_p3 + S*tilde_p3 - T*tilde_p2)/(P*tilde_p2 - P*tilde_p3 - S*tilde_p2 + T*tilde_p3)

Formula for $\text{SSError}$ in terms of a generic measured $p^*$:

In [9]:
p_star = sym.symbols("p_star1:5")

In [10]:
SSError = ((alpha * R + beta * R - P * (alpha + beta) - p_star[0]) ** 2 + 
           (alpha * S + beta * T - P * (alpha + beta) - p_star[1]) ** 2 + 
           (alpha * T + beta * S - P * (alpha + beta) - p_star[2]) ** 2)

In [11]:
SSError

(-P*(alpha + beta) + R*alpha + R*beta - p_star1)**2 + (-P*(alpha + beta) + S*alpha + T*beta - p_star2)**2 + (-P*(alpha + beta) + S*beta + T*alpha - p_star3)**2

Finding optimal value of $\alpha, \beta$:

By differentiating and equating to $0$ we can compute the optimal value of $\alpha$ in terms of $\beta$:

In [12]:
eqn_alpha = sym.solveset(sym.diff(SSError, alpha), alpha).args[0]
eqn_alpha.simplify()

(-3*P**2*beta + 2*P*R*beta + 2*P*S*beta + 2*P*T*beta - P*p_star1 - P*p_star2 - P*p_star3 - R**2*beta + R*p_star1 - 2*S*T*beta + S*p_star2 + T*p_star3)/(3*P**2 - 2*P*R - 2*P*S - 2*P*T + R**2 + S**2 + T**2)

With RPST values:

In [13]:
eqn_alpha.subs({R: 3, P: 1, S: 0, T: 5})

4*beta/21 + 2*p_star1/21 - p_star2/21 + 4*p_star3/21

Differentiating with respect to $\beta$, equating to $0$ and substituting give $\beta$:

In [14]:
eqn_beta = sym.solveset(sym.diff(SSError, beta).subs({alpha: eqn_alpha}), beta)
opt_beta = eqn_beta.args[0]
opt_beta.simplify()

(-3*P**2*p_star2 + 3*P**2*p_star3 + 2*P*R*p_star2 - 2*P*R*p_star3 - P*S*p_star1 + P*S*p_star2 - 3*P*S*p_star3 + P*T*p_star1 + 3*P*T*p_star2 - P*T*p_star3 - R**2*p_star2 + R**2*p_star3 + R*S*p_star1 - R*T*p_star1 + S**2*p_star3 - S*T*p_star2 + S*T*p_star3 - T**2*p_star2)/((S - T)*(6*P**2 - 4*P*R - 4*P*S - 4*P*T + 2*R**2 + S**2 + 2*S*T + T**2))

In [15]:
opt_beta.subs({R: 3, P: 1, S: 0, T: 5})

2*p_star1/17 + 16*p_star2/85 - p_star3/85

For the case of `extort-2`:

In [16]:
opt_beta.subs({p_star[0]: -sym.S(1) / 9, p_star[1]: -sym.S(1) / 2, p_star[2]: sym.S(1) / 3,
               R: 3, P: 1, S: 0, T: 5})

-1/9

We can substitute this back in to our previous expression for $\beta$:

In [17]:
opt_alpha = eqn_alpha.subs({beta: opt_beta})

In [18]:
opt_alpha.simplify()

(3*P**2*p_star2 - 3*P**2*p_star3 - 2*P*R*p_star2 + 2*P*R*p_star3 - P*S*p_star1 - 3*P*S*p_star2 + P*S*p_star3 + P*T*p_star1 - P*T*p_star2 + 3*P*T*p_star3 + R**2*p_star2 - R**2*p_star3 + R*S*p_star1 - R*T*p_star1 + S**2*p_star2 + S*T*p_star2 - S*T*p_star3 - T**2*p_star3)/(6*P**2*S - 6*P**2*T - 4*P*R*S + 4*P*R*T - 4*P*S**2 + 4*P*T**2 + 2*R**2*S - 2*R**2*T + S**3 + S**2*T - S*T**2 - T**3)

For the case of `extort-2`:

In [19]:
opt_alpha.subs({p_star[0]: -sym.S(1) / 9, p_star[1]: -sym.S(1) / 2, p_star[2]: sym.S(1) / 3,
                R: 3, P: 1, S: 0, T: 5})

1/18

The derivative is indeed 0 (in the general case):

In [20]:
sym.diff(SSError, alpha).subs({alpha: opt_alpha, beta:opt_beta}).simplify()

0

In [21]:
sym.diff(SSError, beta).subs({alpha: opt_alpha, beta:opt_beta}).simplify()

0

The actual value of $\chi$:

In [38]:
opt_chi = -opt_beta / opt_alpha
opt_chi.simplify()

(3*P**2*p_star2 - 3*P**2*p_star3 - 2*P*R*p_star2 + 2*P*R*p_star3 + P*S*p_star1 - P*S*p_star2 + 3*P*S*p_star3 - P*T*p_star1 - 3*P*T*p_star2 + P*T*p_star3 + R**2*p_star2 - R**2*p_star3 - R*S*p_star1 + R*T*p_star1 - S**2*p_star3 + S*T*p_star2 - S*T*p_star3 + T**2*p_star2)/(3*P**2*p_star2 - 3*P**2*p_star3 - 2*P*R*p_star2 + 2*P*R*p_star3 - P*S*p_star1 - 3*P*S*p_star2 + P*S*p_star3 + P*T*p_star1 - P*T*p_star2 + 3*P*T*p_star3 + R**2*p_star2 - R**2*p_star3 + R*S*p_star1 - R*T*p_star1 + S**2*p_star2 + S*T*p_star2 - S*T*p_star3 - T**2*p_star3)

In [43]:
sym.solveset(sym.fraction(opt_chi.simplify())[0] - sym.fraction(opt_chi.simplify())[1], p_star[0])

{-(p_star2 + p_star3)*(2*P - S - T)/(2*(P - R))}

In [45]:
(sym.fraction(opt_chi.simplify())[0] - sym.fraction(opt_chi.simplify())[1]).collect(p_star[0]).collect(p_star[1]).collect(p_star[2])

p_star1*(2*P*S - 2*P*T - 2*R*S + 2*R*T) + p_star2*(2*P*S - 2*P*T - S**2 + T**2) + p_star3*(2*P*S - 2*P*T - S**2 + T**2)

In [50]:
((p_star[1]*(2*P*S - 2*P*T - S**2 + T**2) + p_star[2]*(2*P*S - 2*P*T - S**2 + T**2)) / (2*P*S - 2*P*T - 2*R*S + 2*R*T)).simplify()

(2*P*p_star2 + 2*P*p_star3 - S*p_star2 - S*p_star3 - T*p_star2 - T*p_star3)/(2*(P - R))

In [24]:
opt_chi.subs({R: 3, P: 1, S: 0, T: 5}).simplify()

(-10*p_star1 - 16*p_star2 + p_star3)/(10*p_star1 - p_star2 + 16*p_star3)

In [25]:
sym.solveset(sym.fraction(opt_chi.simplify())[0] - sym.fraction(opt_chi.simplify())[1], p_star[0]).subs({R: 3, P: 1, S: 0, T: 5})

{-3*p_star2/4 - 3*p_star3/4}

The actual $\text{SSError}$:

In [26]:
SSError = SSError.subs({alpha:opt_alpha, beta:opt_beta}).factor()
SSError

(2*P*p_star1 - P*p_star2 - P*p_star3 + R*p_star2 + R*p_star3 - S*p_star1 - T*p_star1)**2/(6*P**2 - 4*P*R - 4*P*S - 4*P*T + 2*R**2 + S**2 + 2*S*T + T**2)

In [27]:
SSError.subs({R: 3, P: 1, S: 0, T: 5})

(-3*p_star1 + 2*p_star2 + 2*p_star3)**2/17

In [28]:
p = np.array([8 / 9, 1 / 2, 1 / 3, 0])
p

array([0.88888889, 0.5       , 0.33333333, 0.        ])

In [29]:
zd.compute_least_squares(p)

(array([ 0.05555556, -0.11111111]), 6.256968643151002e-33)

In [30]:
measured_p_star = [p[0] - 1, p[1] - 1, p[2]]
SSError.subs({p_star[i]: measured_p_star[i] for i in range(3)}).subs({R: 3, P: 1, S: 0, T: 5})

0

In [31]:
p = np.array([1, 1 / 2, 1 / 3, 0])
p

array([1.        , 0.5       , 0.33333333, 0.        ])

In [32]:
zd.compute_least_squares(p)

(array([ 0.06862745, -0.09803922]), 0.006535947712418295)

In [33]:
measured_p_star = [p[0] - 1, p[1] - 1, p[2]]
SSError.subs({p_star[i]: measured_p_star[i] for i in range(3)}).subs({R: 3, P: 1, S: 0, T: 5})

0.00653594771241831

In [34]:
p = np.array([0, 1 / 2, 1 / 3, 0])
p

array([0.        , 0.5       , 0.33333333, 0.        ])

In [35]:
zd.compute_least_squares(p)

(array([-0.04901961, -0.21568627]), 0.41830065359477125)

In [36]:
measured_p_star = [p[0] - 1, p[1] - 1, p[2]]
SSError.subs({p_star[i]: measured_p_star[i] for i in range(3)}).subs({R: 3, P: 1, S: 0, T: 5})

0.418300653594771